name: logr

services:
  pg:
    image: timescale/timescaledb:2.24.0-pg18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: logr
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    # for timescaledb background workers
    command: ["postgres", "-c", "shared_preload_libraries=timescaledb"]

volumes:
  pgdata:
