name: logr-db

services:
  postgres:
    image: timescale/timescaledb-ha:pg17
    container_name: logr-pg
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: logr
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    # for timescaledb background workers
    command: ["postgres", "-c", "shared_preload_libraries=timescaledb"]

volumes:
  pgdata:
